image:
  repository: 980218/my-app
  tag: dev

replicaCount: 1

redis:
  enabled: true

postgresql:
  enabled: true

service:
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: Prefix