image:
  repository: 980218/my-app
  tag: dev

replicaCount: 1

redis:
  enabled: true

postgresql:
  enabled: true

  primary:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.3.0-debian-12
    
service:
  port: 3000