image:
  repository: 980218/my-app
  tag: "dev"

replicaCount: 4

redis:
  enabled: true

postgresql:
  enabled: true

service:
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: my-app.prod

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70