image:
  repository: 980218/my-app
  tag: dev

replicaCount: 1

redis:
  enabled: true

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.0.3
  enabled: true

service:
  port: 3000